### ISSUE TITLE
create database model for listing resources

### ISSUE THREAD

**Issue by nikhilyadavnyu** [CSCI-GA-2820-SU23-001/customers#12]
As a Developer
I need to create database model for customer data
So that I could store customer information

Assumptions:
-It will need a database management system known as MySQL
Database model will be implemented using python

Acceptance Criteria 
When search a query to find out a customer information
Given the customer information like first name, last name, one or more addresses, customer ID
Given the userid and password for all customer
Given the customer ID is the primary key of unique identifier 
Then I should retrieve the information of required customer

**Comment by YanChenn** [comment]
Hi, maybe we could make make this issue a little bit more specific: add the SQL queries. Since There is already a ticket on the database management system. We can merge the database model part into the #9

**Comment by nikhilyadavnyu** [comment]
Sure, I will
